// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqCA4tjz2_9xU_1s7Zsxx37IOP-4C4cxk',
    appId: '1:880497198180:web:7d3e94d8c1de7496740b71',
    messagingSenderId: '880497198180',
    projectId: 'flutter-crud-32dfd',
    authDomain: 'flutter-crud-32dfd.firebaseapp.com',
    storageBucket: 'flutter-crud-32dfd.appspot.com',
    measurementId: 'G-4NXN946PKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPCExuJbGe_dI_ZPeKvg6JIh6JhSjqCdU',
    appId: '1:880497198180:android:4d6e138e81d2b4b4740b71',
    messagingSenderId: '880497198180',
    projectId: 'flutter-crud-32dfd',
    storageBucket: 'flutter-crud-32dfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAiAAAXh8tsHKCrBLm84B80RtuWJ30cj0',
    appId: '1:880497198180:ios:72dfef9936000655740b71',
    messagingSenderId: '880497198180',
    projectId: 'flutter-crud-32dfd',
    storageBucket: 'flutter-crud-32dfd.appspot.com',
    iosClientId: '880497198180-7t9g4cahud9t8ksf63v0gj56sfr8f023.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAiAAAXh8tsHKCrBLm84B80RtuWJ30cj0',
    appId: '1:880497198180:ios:72dfef9936000655740b71',
    messagingSenderId: '880497198180',
    projectId: 'flutter-crud-32dfd',
    storageBucket: 'flutter-crud-32dfd.appspot.com',
    iosClientId: '880497198180-7t9g4cahud9t8ksf63v0gj56sfr8f023.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
